# This is a basic workflow to help you get started with Actions

name: Build and Publish

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        id: docker_build
        if: ${{ github.ref_name != 'main' }}
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            valentinriess/chess_frontend:${{ github.ref_name }} 
          # build on feature branches, push only on develop branch
          push: true

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        id: docker_build
        if: ${{ github.ref_name == 'main' }}
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            valentinriess/chess_frontend:latest 
          # build on feature branches, push only on develop branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Webhook Action
        # You may pin to the exact commit or the version.
        # uses: joelwmale/webhook-action@6f6298309b7aa21dc601d8c6271e0be055ce6f0e
        uses: joelwmale/webhook-action@2.1.0
        with:
          # The url to send the webhook event to
          url: https://watchtower.valentinriess.com/v1/update
          # Additional headers to send alongside the defaults
          headers: '{"Authorization": "${{ secrets.WEBHOOK_BEARER }}"}'
          # The data sent to the webhook
          body: ""
          # Enables calling to known self-signed or invalid SSL certificates
          insecure: False
